[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
N8N_HOST = "0.0.0.0"
N8N_PROTOCOL = "https"
N8N_BASIC_AUTH_ACTIVE = "true"
N8N_PORT = "${{PORT}}"

[[volumes]]
mountPath = "/home/node/.n8n"
